// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Storage.App.MVC.Infrastructure.Database;

#nullable disable

namespace Storage.App.MVC.Infrastructure.Database.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20230424112256_Add_ObjectId_ActivityHistoryEntity")]
    partial class Add_ObjectId_ActivityHistoryEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Storage.App.MVC.Core.ActivityHistory.ActivityHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("ActivityHistory");
                });

            modelBuilder.Entity("Storage.App.MVC.Core.Customer.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Storage.App.MVC.Core.Enterprise.EnterpriseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Enterprises");
                });

            modelBuilder.Entity("Storage.App.MVC.Core.Product.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Storage.App.MVC.Core.Sale.SaleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Storage.App.MVC.Core.Sale.SaleItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("Storage.App.MVC.Core.ActivityHistory.ActivityHistoryEntity", b =>
                {
                    b.HasOne("Storage.App.MVC.Core.Enterprise.EnterpriseEntity", "Enterprise")
                        .WithMany("ActivityHistory")
                        .HasForeignKey("EnterpriseId")
                        .IsRequired();

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("Storage.App.MVC.Core.Customer.CustomerEntity", b =>
                {
                    b.HasOne("Storage.App.MVC.Core.Enterprise.EnterpriseEntity", "Enterprise")
                        .WithMany("Customers")
                        .HasForeignKey("EnterpriseId")
                        .IsRequired();

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("Storage.App.MVC.Core.Product.ProductEntity", b =>
                {
                    b.HasOne("Storage.App.MVC.Core.Enterprise.EnterpriseEntity", "Enterprise")
                        .WithMany("Products")
                        .HasForeignKey("EnterpriseId")
                        .IsRequired();

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("Storage.App.MVC.Core.Sale.SaleEntity", b =>
                {
                    b.HasOne("Storage.App.MVC.Core.Customer.CustomerEntity", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .IsRequired();

                    b.HasOne("Storage.App.MVC.Core.Enterprise.EnterpriseEntity", "Enterprise")
                        .WithMany("Sales")
                        .HasForeignKey("EnterpriseId")
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("Storage.App.MVC.Core.Sale.SaleItemEntity", b =>
                {
                    b.HasOne("Storage.App.MVC.Core.Enterprise.EnterpriseEntity", "Enterprise")
                        .WithMany("SaleItems")
                        .HasForeignKey("EnterpriseId")
                        .IsRequired();

                    b.HasOne("Storage.App.MVC.Core.Product.ProductEntity", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.HasOne("Storage.App.MVC.Core.Sale.SaleEntity", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .IsRequired();

                    b.Navigation("Enterprise");

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Storage.App.MVC.Core.Customer.CustomerEntity", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Storage.App.MVC.Core.Enterprise.EnterpriseEntity", b =>
                {
                    b.Navigation("ActivityHistory");

                    b.Navigation("Customers");

                    b.Navigation("Products");

                    b.Navigation("SaleItems");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Storage.App.MVC.Core.Product.ProductEntity", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("Storage.App.MVC.Core.Sale.SaleEntity", b =>
                {
                    b.Navigation("SaleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
